### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by epage** [mj10021/g-win#1]
https://github.com/mj10021/g-win/blob/ae26fe5d99866178f883f8f258283340eb753c24/src/parsers.rs#L12
- `take_till` could instead be done with [`take_until`](https://docs.rs/winnow/latest/winnow/token/fn.take_until.html).  Depending on your benchmarks, `cargo add winnow -F simd` might offer a boost
  - I wish I had a better way of distinguishing these names

https://github.com/mj10021/g-win/blob/ae26fe5d99866178f883f8f258283340eb753c24/src/parsers.rs#L20-L22
- You could just check if its empty or you could use `repeat(0.., parse_line)`

https://github.com/mj10021/g-win/blob/ae26fe5d99866178f883f8f258283340eb753c24/src/parsers.rs#L128-L134
- `line.split_once(';').unwrap_or((line, ""))`

There are likely more opportunities.  Got to switch away though.  Feel free to take or leave any of this.

**Comment by mj10021** [comment]
Hey, thanks for taking a look!

I had initially tried using `repeat0` but was having issues with the parser I wrote getting an error `assert ``repeat` parsers must always consume` failed at ""` which eventually I gave up trying to debug 🤣
